# Generated by Django 4.2.16 on 2025-09-07 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0008_appusermodel_auth_config_userrolemodel_auth_config_and_more'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialapp',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialapp',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='Redirect URL', verbose_name='redirect URL'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appauth.appusermodel'),
        ),
    ]
